### ISSUE TITLE
Is "Keyboard heatmap" still in progress?

### ISSUE THREAD

**Issue by orangetangerine** [KonsomeJona/OctoMouse#17]
I tried "Export stats" but just got a total num of "keystrokes". 
Is the "Keyboard heatmap" still in progress? Or is there a way to know the number of hitting for each key?

**Comment by KonsomeJona** [comment]
Hello and sorry for the late reply. The application is actually recording the number of hitting for each key but this information is not available to the end-user. 
I am sorry I don't have time to work on the keyboard heatmap recently.

**Comment by orangetangerine** [comment]
OK. I took a quick look in code, and I think it's possible to make a heatmap from the data you've already saved. I saw that's stored in a Dict named 'keyCodeDown'. My idea is to export each keycodedown to csv too and make graphics by Python or .
Maybe I could create a PR if you don't mind (well, if I was able to finish it in the future...).

**Comment by orangetangerine** [comment]
![image](https://user-images.githubusercontent.com/4987543/45471021-570dcb80-b762-11e8-9da7-3524bc7dd8eb.png)

I think this is enough for me. But I noticed that <Command> <Shift> <Ctrl> are not recorded and I don't know why. Since I don't have Apple Developer License, I was not able to modify the Mac App

Here is what I have done:
```
plutil -convert xml ~Library/Containers/com.takohi.octomouse/Data/Library/Preferences -o ~/1.xml
```
and make a Python script to generate this image

**Comment by kbrock** [comment]
Nice. I had to specify a different format and tweak the source of the file.

```
plutil -convert xml1 ~/Library/Containers/com.takohi.octomouse/Data/Library/Preferences/com.takohi.octomouse.plist -o ~/1.xml
```

@orangetangerine could you share the script you used to better understand the contents of the file?
If the file were a hash, then that would be easier to understand, but in the current form it is just an array of counts

**EDIT**: Think I got it. [your branch](https://github.com/KonsomeJona/OctoMouse/compare/master...orangetangerine:master) helps explain the key codes

**Comment by orangetangerine** [comment]
Maybe I can put the script in a directory and make a PR to your repo?

**Comment by orangetangerine** [comment]
#28
