### ISSUE TITLE
[Request] Make yesterday's data viewable

### ISSUE THREAD

**Issue by rben01** [KonsomeJona/OctoMouse#2]
I would like to see my mouse usage statistics for a full calendar day. As it stands, I can only view my stats for the day right up until midnight, at which point the stats reset. It would be nice if OctoMouse displayed data for yesterday's mouse usage as well so that we could see an entire day's mouse usage.

**Comment by KonsomeJona** [comment]
Adding a new UI for this feature might take time. 
How about being able to export all the daily data in a CSV file?

**Comment by KonsomeJona** [comment]
Pull Request for this feature:
https://github.com/KonsomeJona/OctoMouse/pull/7
