### ISSUE TITLE
octomouse.takohi.com will be redirected to spam page

### ISSUE THREAD

**Issue by elzup** [KonsomeJona/OctoMouse#29]
on launch pc, this app will open `http://octomouse.takohi.com/?js={...}&sid={...}` by Google Chrome

It's ok, but this page will redirect to Spam page now.
example: (**warning**) `d1jm62qvd5w8ug.cloudfront.net`

OS: macOS 11.2.3
Chrome: 91.0.4472.114 (Default Browser)

**Comment by jorgeyp** [comment]
Same think happens with Firefox, ~~this thing is Malware. Reporting right now.~~

**Comment by jorgeyp** [comment]
Actually... the app itself might not be malware, I think the issue is that upon first launch it opens http://octomouse.takohi.com/#support, but that domain has been taken over by spammers.

**Comment by elzup** [comment]
I got in touch with the developer by Email(@KonsomeJona).
He doesn't seem to have a domain, Mac and development environment anymore.

He says he will accept pull requests that remove the ability to open support links (http://octomouse.takohi.com/#support) at startup.
